spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Appoinment
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: appoinment
